# Image Viewer for all images in a batch

In [1]:
import sys
from pathlib import Path
from typing import List

import json
import matplotlib.pyplot as plt
import numpy as np
from tqdm import tqdm

from topoutils.constants import PROJECT_DIR
from topoutils.sphere_sampling import get_spherical_coordinates
from topoutils.visibility import Vertex, from_json

sys.path.insert(0, '..')

In [71]:
assets = Path(r'd:\android_apps\ImageViewer\app\src\main\assets')
captured_images = assets.joinpath('capturedImages')
cameras_sfm = assets.joinpath('paths', 'cameras.sfm')
output_directory = Path('.').resolve().joinpath('output')
output_directory.mkdir(exist_ok=True)

## Sample polylines
### Green

In [3]:
green_polyline = np.array([
    [2.097919940948E+00, 1.610359922051E-02, 2.190779924393E+00, 255, 255, 255],
    [1.971269965172E+00, 2.922860085964E-01, 2.525049924850E+00, 255, 255, 255],
    [1.777729988098E+00, 6.717010140419E-01, 2.703690052032E+00, 255, 255, 255],
    [1.789610028267E+00, 1.110649943352E+00, 2.692329883575E+00, 255, 255, 255],
    [1.545259952545E+00, 1.343610048294E+00, 2.792229890823E+00, 255, 255, 255],
    [1.419679999352E+00, 2.067719936371E+00, 2.833199977875E+00, 255, 255, 255],
])

### Yellow

In [4]:
yellow_polyline = np.array([
    [8.786039948463E-01, -1.391369998455E-01, 5.187849998474E+00, 255, 255, 255],
    [8.309419751167E-01, 1.031540036201E-01, 5.227940082550E+00, 255, 255, 255],
    [7.717400193214E-01, 1.450600028038E-01, 5.208700180054E+00, 255, 255, 255],
    [5.449720025063E-01, 8.042230010033E-01, 4.987659931183E+00, 255, 255, 255],
    [4.101229906082E-01, 9.882419705391E-01, 4.878980159760E+00, 255, 255, 255],
    [3.861240148544E-01, 1.497460007668E+00, 4.794400215149E+00, 255, 255, 255],
    [2.997510135174E-01, 1.528069972992E+00, 4.036129951477E+00, 255, 255, 255],
    [4.844210147858E-01, 2.060509920120E+00, 4.073040008545E+00, 255, 255, 255]
])

### Blue

In [5]:
blue_polyline = np.array([
    [-6.572080254555E-01, 1.240900039673E+00, 2.931509971619E+00, 255, 255, 255],
    [-6.939949989319E-01, 1.198469996452E+00, 3.038789987564E+00, 255, 255, 255],
    [-6.402289867401E-01, 1.131819963455E+00, 2.981800079346E+00, 255, 255, 255],
    [-5.913980007172E-01, 1.158139944077E+00, 2.861429929733E+00, 255, 255, 255],
    [-6.572080254555E-01, 1.240900039673E+00, 2.931509971619E+00, 255, 255, 255]
])

### Red

In [6]:
red_polyline = np.array([
    [1.359150052071E+00, -4.094719886780E-01, 1.373669981956E+00, 255, 255, 255],
    [1.052219986916E+00, -1.273890025914E-02, 1.117300033569E+00, 255, 255, 255],
    [6.996499896049E-01, 1.551609933376E-01, 1.259979963303E+00, 255, 255, 255],
    [4.651759862900E-01, 2.271769940853E-01, 1.447430014610E+00, 255, 255, 255],
    [5.874119997025E-01, 4.343109950423E-02, 1.556470036507E+00, 255, 255, 255],
    [7.467389702797E-01, -8.026939630508E-02, 1.528660058975E+00, 255, 255, 255],
    [9.594820141792E-01, -2.254000008106E-01, 1.551689982414E+00, 255, 255, 255],
    [1.106259942055E+00, -4.076380133629E-01, 1.612190008163E+00, 255, 255, 255],
    [1.359150052071E+00, -4.094719886780E-01, 1.373669981956E+00, 255, 255, 255]
])

In [7]:
blue_visibility = from_json(PROJECT_DIR.joinpath('visibility', 'BluePolyline.json'))
red_visibility = from_json(PROJECT_DIR.joinpath('visibility', 'RedPolyline.json'))
yellow_visibility = from_json(PROJECT_DIR.joinpath('visibility', 'YellowPolyline.json'))
green_visibility = from_json(PROJECT_DIR.joinpath('visibility', 'GreenPolyline.json'))

In [8]:
polylines = [
    (green_polyline, green_visibility, (0, 1, 0.5)), 
    (yellow_polyline, yellow_visibility, (1, 1, 0)),
    (red_polyline, red_visibility, (1, 0, 0)),
    (blue_polyline, blue_visibility, (0, 170/255, 1)),
]

## Functions

In [9]:
def get_image_coordinates(polyline, K, M):
    polyline = np.hstack((polyline[:,:3], np.ones((polyline.shape[0], 1))))
    points = np.matmul(K, np.matmul(M, polyline.T))
    return np.divide(points, points[-1,:]).astype(int)

In [10]:
def calculate_visibility(vertices: List[Vertex], eye: List[float]) -> np.array:
    n = int(np.sqrt(len(vertices[0].visibility_grid)))
    u, v = get_spherical_coordinates(n)
    P = np.array([[v.x, v.y, v.z] for v in vertices])
    delta = eye - P
    R = np.sqrt(np.sum(np.square(delta), axis=1))
    polar_angle = (np.arccos(delta[:, 2]/R) % np.pi).reshape(-1, 1)
    azimuthal_angle = (np.arctan2(delta[:, 1], delta[:, 0]) % (2 * np.pi)).reshape(-1, 1)
    azimuthal_idx = np.argmin(np.abs(u - azimuthal_angle), axis=1)
    polar_idx = np.argmin(np.abs(v - polar_angle), axis=1)
    poly_vis_idx = polar_idx*n+azimuthal_idx
    nn_visibility = [vertex.visibility_grid[vis_idx] for vis_idx, vertex in zip(poly_vis_idx, vertices)]
    return nn_visibility >= R

In [18]:
def plot_polyline(image_coords, node_visibility, edges, color):
    if not np.any(node_visibility):
        return 
    # plt.scatter(
    #     x=image_coords[:, ~node_visibility][0], 
    #     y=image_coords[:, ~node_visibility][1], 
    #     facecolors='none', 
    #     edgecolors=color
    # )
    plt.scatter(
        x=image_coords[:, node_visibility][0], 
        y=image_coords[:, node_visibility][1], 
        facecolors=color,
        edgecolors=color
    )
    for edge in edges:
        v1_visible = node_visibility[edge.vertex1]
        v2_visible = node_visibility[edge.vertex2]
        coords = image_coords[:, [edge.vertex1, edge.vertex2]]
        if v1_visible and v2_visible:
            plt.plot(coords[0], coords[1], '-', c=color)
        elif v1_visible or v2_visible:
            plt.plot(coords[0], coords[1], '--', c=color)


In [69]:
def is_inside_image(curr_image_coords, image_width, image_height):
    return np.logical_and(
        np.logical_and(
            curr_image_coords[0] >= 0, 
            curr_image_coords[0] <= image_width,
        ),
        np.logical_and(
            curr_image_coords[1] >= 0, 
            curr_image_coords[1] <= image_height
        )
    )

## Camera information

In [12]:
cameras = json.load(cameras_sfm.open('r'))

In [13]:
cameras.keys()

dict_keys(['version', 'featuresFolders', 'matchesFolders', 'views', 'intrinsics', 'poses'])

In [14]:
intrinsic = cameras['intrinsics'][0]

In [15]:
K = np.array([
    [float(intrinsic["pxFocalLength"]), 0, float(intrinsic["principalPoint"][0]), 0],
    [0, float(intrinsic["pxFocalLength"]), float(intrinsic["principalPoint"][1]), 0],
    [0, 0, 1, 0]
])

In [67]:
views = {view['poseId'] : {
    'imgName': view['path'][view['path'].rfind('/')+1:].lower(),
    'width': int(view['width']),
    'height': int(view['height'])
} for view in cameras['views']}    

In [72]:
for pose_obj in tqdm(cameras['poses']):
    pose = pose_obj['pose']['transform']
    view = views[pose_obj['poseId']]
    img_name = view['imgName']
    im = plt.imread(captured_images.joinpath(img_name))
    fig, ax = plt.subplots(figsize=(16,12))
    implot = ax.imshow(im)
    plt.axis('off')
    
    R = np.array([float(x) for x in pose["rotation"]]).reshape((3,3), order='F')
    C = np.array([[float(x)] for x in pose["center"]])
    T = - np.matmul(R, C)
    M = np.vstack((np.hstack((R, T)), np.array([0, 0, 0, 1])))
    eye = [float(x) for x in pose["center"]]
    
    for curr_polyline, curr_visibility, curr_color in polylines:
        curr_image_coords = get_image_coordinates(curr_polyline, K, M)
        curr_is_visible = np.logical_and(
            calculate_visibility(curr_visibility.vertices, eye),
            is_inside_image(curr_image_coords, view['width'], view['height'])
        )
        plot_polyline(curr_image_coords, curr_is_visible, curr_visibility.edges, curr_color)
    plt.savefig(output_directory.joinpath(img_name), bbox_inches='tight')
    plt.close()

100%|██████████████████████████████████████████████████████████████████████████████████| 77/77 [02:21<00:00,  1.84s/it]


In [80]:
for pose_id, view in views.items():
    if view['imgName'] == 'img_20230320_151730.jpg':
        print(pose_id)

1665956728


In [27]:
poses = {pose['poseId']: pose['pose']['transform'] for pose in cameras['poses']}

In [81]:
pose_id = '1665956728'

In [82]:
pose = poses[pose_id]
img_name = views[pose_id]

R = np.array([float(x) for x in pose["rotation"]]).reshape((3,3), order='F')
C = np.array([[float(x)] for x in pose["center"]])
T = - np.matmul(R, C)
M = np.vstack((np.hstack((R, T)), np.array([0, 0, 0, 1])))
eye = [float(x) for x in pose["center"]]

In [83]:
curr_polyline, curr_visibility, curr_color = polylines[2]
curr_image_coords = get_image_coordinates(curr_polyline, K, M)

In [84]:
curr_image_coords

array([[2416, 2717, 3008, 3164, 3040, 2916, 2736, 2610, 2416],
       [2185, 1826, 1678, 1629, 1790, 1894, 2016, 2167, 2185],
       [   1,    1,    1,    1,    1,    1,    1,    1,    1]])

In [85]:
curr_is_visible = calculate_visibility(curr_visibility.vertices, eye)

In [90]:
np.array(curr_visibility.vertices[3].visibility_grid).reshape((8, 8))

array([[7.08068833e+00, 6.96573760e+00, 1.15070185e+01, 1.06268901e+01,
        7.56558915e+00, 6.43693209e+00, 6.52623218e+00, 7.06671033e+00],
       [4.18925280e+00, 7.55833331e+00, 9.39217847e+00, 7.90311859e+00,
        4.20856020e-07, 4.85401048e-07, 1.17039035e-04, 1.09239485e+01],
       [3.95155484e+00,            inf,            inf, 9.53923508e-07,
        6.70684856e-08, 7.29468694e-08, 2.43860496e-06, 6.59604056e+00],
       [5.67978545e+00, 3.99810485e+00, 9.15921886e-01, 1.98173284e-07,
        3.19629721e-08, 3.42170895e-08, 3.10715987e-07, 4.81566845e+00],
       [1.32551100e+00, 3.35407875e-01, 8.89501734e-02, 1.02279026e-07,
        2.38598347e-08, 2.53033686e-08, 1.39804553e-07, 8.00171474e-01],
       [6.67455475e-02, 4.73269451e-02, 3.72960911e-02, 8.01914593e-08,
        2.46537850e-08, 2.59312017e-08, 1.00921203e-07, 7.45884956e-03],
       [1.91265371e-02, 2.14820912e-02, 2.68096160e-06, 8.65986930e-08,
        3.56789887e-08, 3.71538298e-08, 1.01300182e-07, 7.

In [86]:
curr_is_visible

array([ True,  True,  True, False,  True,  True,  True,  True,  True])

In [77]:
img_name

'img_20230320_153614.jpg'

In [78]:
w = 4000
h = 3000

print(np.logical_and(curr_image_coords[0] >= 0, curr_image_coords[0] <= w))
print(np.logical_and(curr_image_coords[1] >= 0, curr_image_coords[1] <= h))

[False False False False False False False False False]
[False False False False False False False False False]
